function leftmenu() {
    document.writeln("<ul class=\'sidebar-menu\' id=\'tmC0\'>");
    document.writeln("  <li id=\'list1001\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-file\'></i><span class=\'menu-text\'>文章系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1001-1\'><a href=\'article-list.html\' target=\'adminbox\'><span class=\'menu-text\'>文章列表</span></a></li>");
    document.writeln("      <li id=\'list1001-2\'><a href=\'article-add.html\' target=\'adminbox\'><span class=\'menu-text\'>添加文章</span></a></li>");
    document.writeln("      <li id=\'list1001-3\'><a href=\'ArticleListDiv.html\' target=\'adminbox\'><span class=\'menu-text\'>文章列表(DIV)</span></a></li>");
    document.writeln("      <li id=\'list1001-3\'><a href=\'ArticleList-grid.html\' target=\'adminbox\'><span class=\'menu-text\'>文章列表(Grid)</span></a></li>");
    document.writeln("      <li id=\'list1001-4\'><a href=\'ClassList.html\' target=\'adminbox\'><span class=\'menu-text\'>栏目管理</span></a></li>");
    document.writeln("      <li id=\'list1001-5\'><a href=\'Recycle.html\' target=\'adminbox\'><span class=\'menu-text\'>回 收 站</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list102\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-image\'></i><span class=\'menu-text\'>图片系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list10002-1\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>图片列表</span></a></li>");
    document.writeln("      <li id=\'list10002-2\'><a href=\'#\'  target=\'adminbox\'><span class=\'menu-text\'>添加图片</span></a></li>");
    document.writeln("      <li id=\'list10002-3\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>审核图片</span></a></li>");
    document.writeln("      <li id=\'list10002-4\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>栏目管理</span></a></li>");
    document.writeln("      <li id=\'list10002-5\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>回 收 站</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list103\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-download\'></i><span class=\'menu-text\'>下载系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list10003-1\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>下载列表</span></a></li>");
    document.writeln("      <li id=\'list10003-2\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>添加下载</span></a></li>");
    document.writeln("      <li id=\'list10003-3\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>审核下载</span></a></li>");
    document.writeln("      <li id=\'list10003-4\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>栏目管理</span></a></li>");
    document.writeln("      <li id=\'list10003-5\'><a href=\'#\' target=\'adminbox\'><span class=\'menu-text\'>回 收 站</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("</ul>");
    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC1\'>");

    document.writeln("  <li id=\'list1101\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-gears\'></i><span class=\'menu-text\'>商城系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1101-1\'><a href=\'Models.html\' target=\'adminbox\'><span class=\'menu-text\'>模型管理首页</span></a></li>");
    document.writeln("      <li id=\'list1101-2\'><a href=\'Modeladd.html\' target=\'adminbox\'><span class=\'menu-text\'>添加新模型</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1102\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-cubes\'></i><span class=\'menu-text\'>模型字段管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1102-1\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>文章系统字段管理</span></a></li>");
    document.writeln("      <li id=\'list1102-2\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>图片系统字段管理</span></a></li>");
    document.writeln("      <li id=\'list1102-3\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>下载系统字段管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("</ul>");

    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC2\'>");

    document.writeln("  <li id=\'list1101\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-gears\'></i><span class=\'menu-text\'>模型管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1101-1\'><a href=\'Models.html\' target=\'adminbox\'><span class=\'menu-text\'>模型管理首页</span></a></li>");
    document.writeln("      <li id=\'list1101-2\'><a href=\'Modeladd.html\' target=\'adminbox\'><span class=\'menu-text\'>添加新模型</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1102\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-cubes\'></i><span class=\'menu-text\'>模型字段管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1102-1\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>文章系统字段管理</span></a></li>");
    document.writeln("      <li id=\'list1102-2\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>图片系统字段管理</span></a></li>");
    document.writeln("      <li id=\'list1102-3\'><a href=\'Model-field.html\' target=\'adminbox\'><span class=\'menu-text\'>下载系统字段管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");

    document.writeln("</ul>");
    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC3\'>");
    document.writeln("  <li id=\'list1201\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-eye\'></i><span class=\'menu-text\'>采集插件</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1201-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>采集项目管理</span></a></li>");
    document.writeln("      <li id=\'list1201-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>采集过滤设置</span></a></li>");
    document.writeln("      <li id=\'list1201-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>采集历史记录</span></a></li>");
    document.writeln("      <li id=\'list1201-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>文档审核入库</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1203\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-superscript\'></i><span class=\'menu-text\'>问答系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1203-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答参数配置</span></a></li>");
    document.writeln("      <li id=\'list1203-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答分类管理</span></a></li>");
    document.writeln("      <li id=\'list1203-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答问题管理</span></a></li>");
    document.writeln("      <li id=\'list1203-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>审核回答</span></a></li>");
    document.writeln("      <li id=\'list1203-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答等级管理</span></a></li>");
    document.writeln("      <li id=\'list1203-6\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答专家管理</span></a></li>");
    document.writeln("      <li id=\'list1203-7\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>问答数据表管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1204\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-users\'></i><span class=\'menu-text\'>微社区系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1204-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>微社区参数配置</span></a></li>");
    document.writeln("      <li id=\'list1204-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>微社区版面管理</span></a></li>");
    document.writeln("      <li id=\'list1204-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>微社区话题管理</span></a></li>");
    document.writeln("      <li id=\'list1204-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>审核话题回复</span></a></li>");
    document.writeln("      <li id=\'list1204-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>微社区等级管理</span></a></li>");
    document.writeln("      <li id=\'list1204-6\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>微社区数据表管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1205\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-asterisk\'></i><span class=\'menu-text\'>空间系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1205-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>空间参数设置</span></a></li>");
    document.writeln("      <li id=\'list1205-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>个人空间管理</span></a></li>");
    document.writeln("      <li id=\'list1205-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>空间博文管理</span></a></li>");
    document.writeln("      <li id=\'list1205-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>空间相册管理</span></a></li>");
    document.writeln("      <li id=\'list1205-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>空间留言管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1206\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-comments\'></i><span class=\'menu-text\'>留言系统</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1206-\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>留言管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1207\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-user-plus\'></i><span class=\'menu-text\'>友情链接</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1207-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>友情链接</span></a></li>");
    document.writeln("      <li id=\'list1207-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>分类管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1208\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-bar-chart\'></i><span class=\'menu-text\'>投票调查</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1208-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>投票主题</span></a></li>");
    document.writeln("      <li id=\'list1208-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>投票记录</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1209\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-random\'></i><span class=\'menu-text\'>PK管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1209-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>PK主题管理</span></a></li>");
    document.writeln("      <li id=\'list1209-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>PK意见管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1210\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-tasks\'></i><span class=\'menu-text\'>自定义表单</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1210-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>表单项目管理</span></a></li>");
    document.writeln("      <li id=\'list1210-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>提交记录</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1211\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-audio-description\'></i><span class=\'menu-text\'>广告管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1211-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>广告位分类</span></a></li>");
    document.writeln("      <li id=\'list1211-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>广告位管理</span></a></li>");
    document.writeln("      <li id=\'list1211-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>所有广告</span></a></li>");
    document.writeln("      <li id=\'list1211-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>生成所有广告位</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("</ul>");

    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC4\'>");
    document.writeln("  <li id=\'list1301\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-tag\'></i><span class=\'menu-text\'>标签管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1301-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>系统函数标签</span></a></li>");
    document.writeln("      <li id=\'list1301-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>自定义SQL函数标签</span></a></li>");
    document.writeln("      <li id=\'list1301-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>自定义静态标签</span></a></li>");
    document.writeln("      <li id=\'list1301-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>自定义生成XML文档</span></a></li>");
    document.writeln("      <li id=\'list1301-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>分页样式管理</span></a></li>");
    document.writeln("      <li id=\'list1301-6\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>系统JS管理</span></a></li>");
    document.writeln("      <li id=\'list1301-7\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>自定义JS管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");

    document.writeln("  <li id=\'list1302\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-television\'></i><span class=\'menu-text\'>模板管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1302-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>所有模板管理</span></a></li>");
    document.writeln("      <li id=\'list1302-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>自定义页面管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("</ul>");
    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC5\'>");
    document.writeln("  <li id=\'list1401\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-user\'></i><span class=\'menu-text\'>用户管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1401-1\'><a href=\'Userlist.html\' target=\'adminbox\'><span class=\'menu-text\'>注册用户管理</span></a></li>");
    document.writeln("      <li id=\'list1401-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>添加用</span>户</a></li>");
    document.writeln("      <li id=\'list1401-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>用户组管理</span></a></li>");
    document.writeln("      <li id=\'list1401-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>用户短信管理</span></a></li>");
    document.writeln("      <li id=\'list1401-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>发送邮件管理</span></a></li>");
    document.writeln("      <li id=\'list1401-6\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员字段管理</span></a></li>");
    document.writeln("      <li id=\'list1401-7\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员表单管理</span></a></li>");
    document.writeln("      <li id=\'list1401-8\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员使用记录</span></a></li>");
    document.writeln("      <li id=\'list1401-9\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员签到管理</span></a></li>");
    document.writeln("      <li id=\'list1401-10\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>推广计划管理</span></a></li>");
    document.writeln("      <li id=\'list1401-11\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员稿件统计</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1402\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-user-plus\'></i><span class=\'menu-text\'>管理员管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1402-1\'><a href=\'AdminUser.html\' target=\'adminbox\'><span class=\'menu-text\'>管理员管理</span></a></li>");
    document.writeln("      <li id=\'list1402-2\'><a href=\'AdminUserOp.html\' target=\'adminbox\'><span class=\'menu-text\'>管理员角色</span></a></li>");
    document.writeln("      <li id=\'list1402-3\'><a href=\'AdminUserSign.html\' target=\'adminbox\'><span class=\'menu-text\'>登陆记录</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1403\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-credit-card\'></i><span class=\'menu-text\'>用户财务管理</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1403-1\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员点券明细</span></a></li>");
    document.writeln("      <li id=\'list1403-2\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员有效期明细</span></a></li>");
    document.writeln("      <li id=\'list1403-3\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员资金明细</span></a></li>");
    document.writeln("      <li id=\'list1403-4\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>会员积分明细</span></a></li>");
    document.writeln("      <li id=\'list1403-5\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>线下充值卡管理</span></a></li>");
    document.writeln("      <li id=\'list1403-6\'><a href=\'.html\' target=\'adminbox\'><span class=\'menu-text\'>线上充值卡管理</span></a></li>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("");
    document.writeln("");
    document.writeln("</ul>");
    document.writeln("<ul class=\'sidebar-menu none\' id=\'tmC6\'>");
    document.writeln("  <li id=\'list1501\' class=\'open active\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-terminal\'></i><span class=\'menu-text\'>系统配置</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1501-1\'><a href=\'system.html\' target=\'adminbox\'><span class=\'menu-text\'>系统参数配置</span></a>");
    document.writeln("      <li id=\'list1501-2\'><a href=\'SystemSafe.html\' target=\'adminbox\'><span class=\'menu-text\'>系统安全设置</span></a>");
    document.writeln("      <li id=\'list1501-3\'><a href=\'ReWrite.html\' target=\'adminbox\'><span class=\'menu-text\'>伪静态规则管理</span></a>");
    document.writeln("      <li id=\'list1501-4\'><a href=\'ClassList.html\' target=\'adminbox\'><span class=\'menu-text\'>栏目管理</span></a>");
    document.writeln("      <li id=\'list1501-5\'><a href=\'paykinds.html\' target=\'adminbox\'><span class=\'menu-text\'>支付平台设置</span></a>");
    document.writeln("      <li id=\'list1501-6\'><a href=\'Api.html\' target=\'adminbox\'><span class=\'menu-text\'>API整合设置</span></a>");
    document.writeln("    </ul>");
    document.writeln("  </li>");
    document.writeln("  <li id=\'list1502\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-database\'></i><span class=\'menu-text\'>数据库维护</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1502-1\'><a href=\'Database.html\' target=\'adminbox\'><span class=\'menu-text\'>数据库维护工具</span></a>");
    document.writeln("      <li id=\'list1502-2\'><a href=\'Datafiledchange.html\' target=\'adminbox\'><span class=\'menu-text\'>数据库字段值替换</span></a>");
    document.writeln("      <li id=\'list1502-3\'><a href=\'DataSQL.html\' target=\'adminbox\'><span class=\'menu-text\'>在线执行SQL语句</span></a>");
    document.writeln("      <li id=\'list1502-5\'><a href=\'DataGroupFilein.html\' target=\'adminbox\'><span class=\'menu-text\'>数据批量导入工具</span></a>");
    document.writeln("      <li id=\'list1502-6\'><a href=\'Onkeytool.html\' target=\'adminbox\'><span class=\'menu-text\'>一键管理工具</span></a>");
    document.writeln("      <li id=\'list1502-7\'><a href=\'DateModelchange.html\' target=\'adminbox\'><span class=\'menu-text\'>模型数据移动工具</span></a>");
    document.writeln("      <li id=\'list1502-8\'><a href=\'ServerTool.html\' target=\'adminbox\'><span class=\'menu-text\'>服务器参数探测工具</span></a>");
    document.writeln("    </ul>");
    document.writeln("  </li>");

    document.writeln("  <li id=\'list1503\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-cogs\'></i><span class=\'menu-text\'>其他系统配置</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1503-1\'><a href=\'InerLink.html\' target=\'adminbox\'><span class=\'menu-text\'>内部链接管理</span></a>");
    document.writeln("      <li id=\'list1503-2\'><a href=\'Area.html\' target=\'adminbox\'><span class=\'menu-text\'>地区设置管理</span></a>");
    document.writeln("      <li id=\'list1503-3\'><a href=\'Ctrlog.html\' target=\'adminbox\'><span class=\'menu-text\'>操作日志管理</span></a>");
    document.writeln("      <li id=\'list1503-4\'><a href=\'Pageno.html\' target=\'adminbox\'><span class=\'menu-text\'>显示条数管理</span></a>");
    document.writeln("      <li id=\'list1503-5\'><a href=\'File.html\' target=\'adminbox\'><span class=\'menu-text\'>文件管理器</span></a>");
    document.writeln("      <li id=\'list1503-6\'><a href=\'Updatefiles.html\' target=\'adminbox\'><span class=\'menu-text\'>上传文件管理</span></a>");
    document.writeln("      <li id=\'list1503-7\'><a href=\'DataDick.html\' target=\'adminbox\'><span class=\'menu-text\'>数据字典</span></a>");
    document.writeln("      <li id=\'list1503-7\'><a href=\'AuthorOrgin.html\' target=\'adminbox\'><span class=\'menu-text\'>作者/来源/关键字</span></a>");
    document.writeln("    </ul>");
    document.writeln("  </li>");

    document.writeln("  <li id=\'list1504\'><a href=\'javascript:void(0)\' class=\'menu-dropdown\'><i class=\'menu-icon fa fa-cogs\'></i><span class=\'menu-text\'>其他页面</span><i class=\'fa fa-angle-right menu-expand\'></i></a>");
    document.writeln("    <ul class=\'submenu\'>");
    document.writeln("      <li id=\'list1504-1\'><a href=\'login.html\' target=\'_blank\'><span class=\'menu-text\'>登录页面</span></a>");
    document.writeln("    </ul>");
    document.writeln("  </li>");


    document.writeln("</ul>");
}
