(function (window, $, undefined) {

    //构建函数：广告控制,随机图片、动画、文字、网页兼容手机端
$.fn.thinkads=function(options){var ad={folder:[{res:"",url:"",mres:"",murl:""}],rand:1,pos:1,display:"",margin:"",mdisplay:"",mmargin:""};if(options){$.extend(ad,options)};this.each(function(){var pcdisplay=ad.display,pcmargin=ad.margin;var mbdisplay=ad.mdisplay,mbmargin=ad.mmargin;var gpos=ad.pos;if(gpos==1){$(this).append("<div class='eye'>广告</div>")}function mixArray(source){var goal=[];for(var i=0;i<source.length;i++){var pos=Math.floor(Math.random()*(source.length-i));goal[i]=source[pos];source[pos]=source[source.length-1-i]}return goal}var ro=new Array();for(var x=0;x<ad.folder.length;x++){ro[x]=x};ro=mixArray(ro);for(var j=0;j<ad.rand;j++){var pctempltet="",mbtempltet="";var pcres=ad.folder[ro[j]].res,pcurl=ad.folder[ro[j]].url;var mbres=ad.folder[ro[j]].mres,mburl=ad.folder[ro[j]].murl;pctempltet="<div class='hid-xs'><a href='"+pcurl+"' target='_blank'><img src="+pcres+"></a></div>";mbtempltet="<div class='hid-sm'><a href='"+mburl+"' target='_blank'><img src="+mbres+"></a></div>";(device.mobile())?$(this).append(mbtempltet):$(this).append(pctempltet)}(device.mobile())?$(this).css({"margin":mbmargin}):$(this).css({"margin":pcmargin});if(mbdisplay=='none'){$(this).css({"display":"none"})}if(pcdisplay=='none'){$(this).css({"display":"none"})}})}

//eval(function(p,a,c,k,e,r){e=function(c){return(c<62?'':e(parseInt(c/62)))+((c=c%62)>35?String.fromCharCode(c+29):c.toString(36))};if('0'.replace(0,e)==0){while(c--)r[e(c)]=k[c];k=[function(e){return r[e]||e}];e=function(){return'[2-9b-hk-wyzA-R]'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$.fn.thinkads=h(k){2 3={7:[{r:"",s:"",t:"",u:""}],v:1,9:1,b:"",c:"",w:"",y:""};d(k){$.extend(3,k)};4.each(h(){2 z=3.b,A=3.c;2 B=3.w,C=3.y;2 D=3.9;d(D==1){$(4).l("<8 m=\'eye\'>广告</8>")}h E(6){2 n=[];o(2 i=0;i<6.e;i++){2 9=F.floor(F.random()*(6.e-i));n[i]=6[9];6[9]=6[6.e-1-i]}return n}2 5=new Array();o(2 x=0;x<3.7.e;x++){5[x]=x};5=E(5);o(2 j=0;j<3.v;j++){2 p="",q="";2 G=3.7[5[j]].r,H=3.7[5[j]].s;2 I=3.7[5[j]].t,J=3.7[5[j]].u;p="<8 m=\'K-xs\'><a L=\'"+H+"\' M=\'N\'><O P="+G+"></a></8>";q="<8 m=\'K-sm\'><a L=\'"+J+"\' M=\'N\'><O P="+I+"></a></8>";(Q.R())?$(4).l(q):$(4).l(p)}(Q.R())?$(4).f({"c":C}):$(4).f({"c":A});d(B==\'g\'){$(4).f({"b":"g"})}d(z==\'g\'){$(4).f({"b":"g"})}})}',[],54,'||var|ad|this|ro|source|folder|div|pos||display|margin|if|length|css|none|function|||options|append|class|goal|for|pctempltet|mbtempltet|res|url|mres|murl|rand|mdisplay||mmargin|pcdisplay|pcmargin|mbdisplay|mbmargin|gpos|mixArray|Math|pcres|pcurl|mbres|mburl|hid|href|target|_blank|img|src|device|mobile'.split('|'),0,{}))
})(window, jQuery);

//负载函数

